#!/bin/bash
set -euo pipefail

mods=/var/lib/kernel-update-hook/modules
if [ ! -e $mods ]; then
    mkdir -p "$(dirname $mods)"
    touch $mods
fi

awk '{print $1}' /proc/modules | sort -u - $mods > $mods.tmp
mv $mods.tmp $mods
